name: Jest unit tests

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    # Jest unit tests
    - name: Run Jest unit-tests
      run: npm run test:unit

    # Add coverage badge
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}